---
name: Build target url list

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - run: pip install -r ./builder/requirements.txt
      - run: python3 ./builder/main.py
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build target url list
