name: Build DAP Top 100,000 source List

# yamllint disable-line rule:truthy
on:
  schedule:
    - cron: "00 21 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.9"
      - run: pip install -r ./dapDataCollapse/requirements.txt
      - run: python3 ./dapDataCollapse/main.py
      - uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7.1.0
        with:
          commit_message: Build DAP Top 100000 List
