name: Build final URL list

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "30 20 * * *"

jobs:
  my-job:
    name: Checkout, build, and run final URL list builder
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          cd builder
          bun install

      - name: Run indexer application
        run: |
          cd builder
          bun src/finalUrlBuilder.ts

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build final URL list