name: Build target url list using TypeScript

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  schedule:
    - cron: "15 20 * * *"

jobs:
  my-job:
    name: Checkout, build, and run indexer application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: |
          cd builder-js
          bun install

      - name: Run indexer application
        run: |
          cd builder
          bun src/main.ts

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Build target url list